config/routes.rb
Rails.application.routes.draw do

  scope :init, as: :init do
    get 'index', to: 'initial_settings#index'
    get 'setting', to: 'initial_settings#setting'
    post 'setting', to: 'initial_settings#create_setting'
    get 'completion', to: 'initial_settings#completion'
  end

  namespace :admin do
    get 'settings/index'
  end

  authenticated :user do
    namespace :admin do
      resources :articles do
        collection do
          post 'preview'
        end
      end
      resources :categories
      resources :tags
      resources :images

      get '/', to: 'dashboard#index'
      get 'settings', to: 'settings#index'
      patch 'settings', to: 'settings#update'

      # resource :users, only: %i[index edit update]
      authenticated :user, lambda { |u| u.admin? } do
        get 'users', to: 'users#index'
        get 'users/index'
      end
    end
  end

  resources :tags, only: %i[index show]
  resources :categories, only: %i[index show]
  resources :articles, param: :permalink, only: %i[index show]

  devise_for :users, path: 'admin/users', controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'admin/users/:id/edit', to: 'users/registrations#other_edit', as: :edit_admin_user
    put 'admin/users/:id', to: 'users/registrations#other_update', as: :admin_user
    delete 'admin/users/:id', to: 'users/registrations#other_destroy'
  end

  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  enum status: { draft: 0, publication: 1 }
  enum document_type: { html: 0, markdown: 1 }

  after_commit :update_sitemap
  after_destroy :update_sitemap

  has_many :article_drafts, dependent: :delete_all
  has_many :category_articles, dependent: :delete_all
  has_many :categories, through: :category_articles
  has_many :tag_articles, dependent: :delete_all
  has_many :tags, through: :tag_articles
  has_many :user_articles, dependent: :delete_all
  has_many :users, through: :user_articles

  validates :title, presence: true
  validates :status,
            presence: true,
            inclusion: { in: Article.statuses.keys }
  validates :document_type,
            presence: true,
            inclusion: { in: Article.document_types.keys }
  validates :permalink,
            presence: true,
            uniqueness: true,
            length: { maximum: 128 },
            format: { with: /\A[A-Za-z0-9\-_]+\z/ }

  validate :check_publication_date_presence

  scope :only_publication, -> { where(status: Article.statuses[:publication]).where('publication_date <= ?', Time.zone.now) }

  private

  def check_publication_date_presence
    errors.add(:publication_date, "can't be blank") if publication? && publication_date.blank?
  end

  def update_sitemap
    Rails.application.load_tasks
    Rake::Task['sitemap:generate'].execute
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  protect_from_forgery except: :preview
  before_action :set_article, only: %i[show edit update destroy]

  # GET /admin/articles
  # GET /admin/articles.json
  def index
    @articles = Article.all
  end

  # GET /admin/articles/1
  # GET /admin/articles/1.json
  def show; end

  def preview
    @article = Article.new(article_params)

    render template: 'articles/show', layout: 'application'
  end

  # GET /admin/articles/new
  def new
    @image = Image.new
    @images = Image.all
    @article = Article.new
  end

  # GET /admin/articles/1/edit
  def edit
    @image = Image.new
    @images = Image.all
  end

  # POST /admin/articles
  # POST /admin/articles.json
  def create
    @article = Article.new(article_params)
    @article.user_ids = [current_user.id]

    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_article_url(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/articles/1
  # PATCH/PUT /admin/articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to admin_article_url(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.fetch(:article, {}).permit(:title, :body, :document_type, :permalink, :status, :publication_date, category_ids: [], tag_ids: [])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.only_publication
  end

  # GET /articles/1
  # GET /articles/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find_by!(permalink: params[:permalink], status: Article.statuses[:publication])
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_media.html.erb
<div class="text-right">
  <i class="fas fa-times modal-remove-icon"></i>
</div>

<%= button_tag 'Add image', type: 'button', class: 'btn btn-outline-dark modal-image-addition-button' %>
<div class="modal-image-addition-form">
  <%= form_with(model: image, local: true, url: admin_images_path) do |form| %>
    <% if image.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(image.errors.count, "error") %> prohibited this article from being saved:</h2>

        <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :image %><br />
      <%= form.file_field :image, id: :image_image %>
    </div>

    <div class="field">
      <%= form.label :alt %><br />
      <%= form.text_field :alt, id: :image_alt %>
    </div>

    <div class="field">
      <%= form.label :title %><br />
      <%= form.text_field :title, id: :image_title %>
    </div>

    <div class="actions">
      <%= form.submit id: 'modal-image-submit-button' %>
    </div>
  <% end %>
</div>

<div class="modal-images">
  <div class="row">
    <% images.find_each do |img| %>
      <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">
        <div class="card" style="margin-bottom: 1rem;">
          <%= image_tag img.image, title: img.title.to_s, alt: img.alt.to_s, class: 'card-img-top modal-image' %>
          <div class="modal-image-info">
            <%= hidden_field_tag :image_url, img.image %>
            <%= hidden_field_tag :alt, img.alt %>
            <%= hidden_field_tag :title, img.title %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/articles/edit.html.erb
<h1>Editing Article</h1>

<div class="article-media-modal-background"></div>
<div class="article-media-modal">
  <%= render partial: 'media', locals: { image: @image, images: @images } %>
</div>

<%= form_with(model: @article, local: true, url: admin_article_path) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %><br />
    <%= form.select :status, Article.statuses.keys %>
  </div>

  <div class="field">
    <%= form.label :publication_date %>
    <%= form.datetime_select :publication_date %><%= Time.zone.now.time_zone.name %>
  </div>

  <div class="field">
    <%= form.label :document_type %><br />
    <%= form.select :document_type, Article.document_types.keys %>
  </div>

  <div class="field">
    <%= form.label :permalink %><br />
    <%= form.text_field :permalink %>
  </div>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="field">
    <%= form.label :body %> <%= button_tag 'Add media', type: "button", class: 'article-media-button' %><br />
    <%= form.text_area :body, id: :article_body %>
  </div>

  <div class="field">
    <%= form.label :categories %><br />
    <%= collection_check_boxes(:article, :category_ids, Category.all, :id, :title) do |ccb| %>
      <%= ccb.label { ccb.check_box + ccb.text } %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :tags %><br />
    <%= collection_check_boxes(:article, :tag_ids, Tag.all, :id, :title) do |ccb| %>
      <%= ccb.label { ccb.check_box + ccb.text } %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit class: 'article-submit-button', 'data-action': admin_articles_path %>
    <%= form.submit 'Preview', class: 'article-preview-button', 'data-action': preview_admin_articles_path %>
  </div>
<% end %>

<%= link_to 'Show', admin_article_path(@article) %> |
<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/index.html.erb
<h1>Articles</h1>

<%= link_to 'New Admin Article', new_admin_article_path, class: 'new-article-button btn btn-outline-dark' %>

<ul class="article-list">
  <% @articles.each do |article| %>
    <li>
      <div>
        <h2><%= article.title %></h2>
        <p>status: <%= article.status %></p>
        <% if article.publication? %>
          <p>publication date: <%= article.publication_date %>
        <% end %>
        <div class="article-menu">
          <%= link_to 'Show', admin_article_path(article) %>
          <%= link_to 'Edit', edit_admin_article_path(article) %>
          <%= link_to 'Destroy', admin_article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>

<div class="article-media-modal-background"></div>
<div class="article-media-modal">
  <%= render partial: 'media', locals: { image: @image, images: @images } %>
</div>

<%= form_with(model: @article, local: true, url: admin_articles_path) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %><br />
    <%= form.select :status, Article.statuses.keys %>
  </div>

  <div class="field">
    <%= form.label :publication_date %>
    <%= form.datetime_select :publication_date, id: :publication_date %><%= Time.zone.now.time_zone.name %>
  </div>

  <div class="field">
    <%= form.label :document_type %><br />
    <%= form.select :document_type, Article.document_types.keys, id: :article_document_type %>
  </div>

  <div class="field">
    <%= form.label :permalink %><br />
    <%= form.text_field :permalink, id: :article_permalink %>
  </div>

  <div class="field">
    <%= form.label :title %><br/>
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="field">
    <%= form.label :body %> <%= button_tag 'Add media', type: "button", class: 'article-media-button' %><br />
    <%= form.text_area :body, id: :article_body %>
  </div>

  <div class="field">
    <%= form.label :categories %><br />
    <%= collection_check_boxes(:article, :category_ids, Category.all, :id, :title) do |ccb| %>
      <%= ccb.label { ccb.check_box + ccb.text } %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :tags %><br />
    <%= collection_check_boxes(:article, :tag_ids, Tag.all, :id, :title) do |ccb| %>
      <%= ccb.label { ccb.check_box + ccb.text } %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit class: 'article-submit-button', 'data-action': admin_articles_path %>
    <%= form.submit 'Preview', class: 'article-preview-button', 'data-action': preview_admin_articles_path %>
  </div>
<% end %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<h2><%= @article.title %></h2>

<% if @article.publication? %>
  <p>
    URL: <%= link_to article_url(@article.permalink), article_path(@article.permalink) %>
  </p>
<% end %>

<p>
  status: <%= @article.status %>
</p>

<% if @article.publication? %>
  <p>
    publication date: <%= @article.publication_date %>
  </p>
<% end %>

<p>
  document_type: <%= @article.document_type %>
</p>

<div class="article-body">
  <% if @article.html? %>
    <p>
      <%= @article.body %>
    </p>
  <% elsif @article.markdown? %>
    <%= sanitize markdown(@article.body) %>
  <% end %>
</div>

<div class="article-category">
  <h3>Categories</h3>
  <% @article.categories.each do |category| %>
    <%= category.title %><br />
  <% end %>
</div>

<div class="article-tag">
  <h3>Tags</h3>
  <% @article.tags.each do |tag| %>
    <%= tag.title %><br />
  <% end %>
</div>

<%= link_to 'Edit', edit_admin_article_path(@article) %> |
<%= link_to 'Back', admin_articles_path %>