config/routes.rb
Rails.application.routes.draw do

  scope :init, as: :init do
    get 'index', to: 'initial_settings#index'
    get 'setting', to: 'initial_settings#setting'
    post 'setting', to: 'initial_settings#create_setting'
    get 'completion', to: 'initial_settings#completion'
  end

  namespace :admin do
    get 'settings/index'
  end

  authenticated :user do
    namespace :admin do
      resources :articles do
        collection do
          post 'preview'
        end
      end
      resources :categories
      resources :tags
      resources :images

      get '/', to: 'dashboard#index'
      get 'settings', to: 'settings#index'
      patch 'settings', to: 'settings#update'

      # resource :users, only: %i[index edit update]
      authenticated :user, lambda { |u| u.admin? } do
        get 'users', to: 'users#index'
        get 'users/index'
      end
    end
  end

  resources :tags, only: %i[index show]
  resources :categories, only: %i[index show]
  resources :articles, param: :permalink, only: %i[index show]

  devise_for :users, path: 'admin/users', controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'admin/users/:id/edit', to: 'users/registrations#other_edit', as: :edit_admin_user
    put 'admin/users/:id', to: 'users/registrations#other_update', as: :admin_user
    delete 'admin/users/:id', to: 'users/registrations#other_destroy'
  end

  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_articles, dependent: :delete_all
  has_many :articles, through: :category_articles

  validates :title, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @categories = Category.all
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show; end

  # GET /admin/categories/new
  def new
    @category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit; end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1
  # PATCH/PUT /admin/categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.fetch(:category, {}).permit(:title, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :category_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :category_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Admin Category</h1>

<%= form_with(model: @category, local: true, url: admin_category_path(@category)) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :category_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :category_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', admin_category_path(category) %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
        <td><%= link_to 'Destroy', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Category', new_admin_category_path %>

app/views/admin/categories/new.html.erb
<h1>New Admin Category</h1>

<%= form_with(model: @category, local: true, url: admin_categories_path) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :category_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :category_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>