config/routes.rb
Rails.application.routes.draw do

  scope :init, as: :init do
    get 'index', to: 'initial_settings#index'
    get 'setting', to: 'initial_settings#setting'
    post 'setting', to: 'initial_settings#create_setting'
    get 'completion', to: 'initial_settings#completion'
  end

  namespace :admin do
    get 'settings/index'
  end

  authenticated :user do
    namespace :admin do
      resources :articles do
        collection do
          post 'preview'
        end
      end
      resources :categories
      resources :tags
      resources :images

      get '/', to: 'dashboard#index'
      get 'settings', to: 'settings#index'
      patch 'settings', to: 'settings#update'

      # resource :users, only: %i[index edit update]
      authenticated :user, lambda { |u| u.admin? } do
        get 'users', to: 'users#index'
        get 'users/index'
      end
    end
  end

  resources :tags, only: %i[index show]
  resources :categories, only: %i[index show]
  resources :articles, param: :permalink, only: %i[index show]

  devise_for :users, path: 'admin/users', controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'admin/users/:id/edit', to: 'users/registrations#other_edit', as: :edit_admin_user
    put 'admin/users/:id', to: 'users/registrations#other_update', as: :admin_user
    delete 'admin/users/:id', to: 'users/registrations#other_destroy'
  end

  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :image, presence: true
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < AdminController
  before_action :set_image, only: %i[show edit update destroy]

  def index
    @images = Image.all
  end

  def show; end

  def new
    @image = Image.new
  end

  def edit; end

  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to admin_image_url(@image), notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: admin_image_url(@image) }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to admin_image_url(@image), notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_image_url(@image) }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to admin_images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.fetch(:image, {}).permit(:image, :alt, :title)
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/views/admin/images/edit.html.erb
<h1>Editing Admin Image</h1>

<%= form_with(model: @image, local: true, url: admin_image_path(@image)) do |form| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this admin_image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :image_image %>
  </div>

  <div class="field">
    <%= form.label :alt %>
    <%= form.text_field :alt, id: :image_alt %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :image_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', admin_images_path %>

app/views/admin/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Images</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Alt</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.image %></td>
        <td><%= image.alt %></td>
        <td><%= image.title %></td>
        <td><%= link_to 'Show', admin_image_path(image) %></td>
        <td><%= link_to 'Edit', edit_admin_image_path(image) %></td>
        <td><%= link_to 'Destroy', admin_image_path(image), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Image', new_admin_image_path %>

app/views/admin/images/new.html.erb
<h1>New Admin Image</h1>

<%= form_with(model: @image, local: true, url: admin_images_path) do |form| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this admin_image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :image_image %>
  </div>

  <div class="field">
    <%= form.label :alt %>
    <%= form.text_field :alt, id: :image_alt %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :image_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', admin_images_path %>

app/views/admin/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @image.image %>
</p>

<p>
  <strong>Alt:</strong>
  <%= @image.alt %>
</p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<%= link_to 'Edit', edit_admin_image_path(@image) %> |
<%= link_to 'Back', admin_images_path %>