config/routes.rb
Rails.application.routes.draw do

  scope :init, as: :init do
    get 'index', to: 'initial_settings#index'
    get 'setting', to: 'initial_settings#setting'
    post 'setting', to: 'initial_settings#create_setting'
    get 'completion', to: 'initial_settings#completion'
  end

  namespace :admin do
    get 'settings/index'
  end

  authenticated :user do
    namespace :admin do
      resources :articles do
        collection do
          post 'preview'
        end
      end
      resources :categories
      resources :tags
      resources :images

      get '/', to: 'dashboard#index'
      get 'settings', to: 'settings#index'
      patch 'settings', to: 'settings#update'

      # resource :users, only: %i[index edit update]
      authenticated :user, lambda { |u| u.admin? } do
        get 'users', to: 'users#index'
        get 'users/index'
      end
    end
  end

  resources :tags, only: %i[index show]
  resources :categories, only: %i[index show]
  resources :articles, param: :permalink, only: %i[index show]

  devise_for :users, path: 'admin/users', controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'admin/users/:id/edit', to: 'users/registrations#other_edit', as: :edit_admin_user
    put 'admin/users/:id', to: 'users/registrations#other_update', as: :admin_user
    delete 'admin/users/:id', to: 'users/registrations#other_destroy'
  end

  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_syntax_highlight.html.erb
<style type="text/css">
  <% case syntax_highlight %>
  <% when 'base16 light' %>
    <%= Rouge::Themes::Base16.mode(:light).render(scope: '.highlight') %>
  <% when 'base16 dark' %>
    <%= Rouge::Themes::Base16.mode(:dark).render(scope: '.highlight') %>
  <% when 'colorful' %>
    <%= Rouge::Themes::Colorful.render(scope: '.highlight') %>
  <% when 'github' %>
    <%= Rouge::Themes::Github.render(scope: '.highlight') %>
  <% when 'gruvbox light' %>
    <%= Rouge::Themes::Gruvbox.mode(:light).render(scope: '.highlight') %>
  <% when 'gruvbox dark' %>
    <%= Rouge::Themes::Gruvbox.mode(:dark).render(scope: '.highlight') %>
  <% when 'igor_pro' %>
    <%= Rouge::Themes::IgorPro.render(scope: '.highlight') %>
  <% when 'molokai' %>
    <%= Rouge::Themes::Molokai.render(scope: '.highlight') %>
  <% when 'monokai' %>
    <%= Rouge::Themes::Monokai.render(scope: '.highlight') %>
  <% when 'monokai sublime' %>
    <%= Rouge::Themes::MonokaiSublime.render(scope: '.highlight') %>
  <% when 'pastie' %>
    <%= Rouge::Themes::Pastie.render(scope: '.highlight') %>
  <% when 'thankful eyes' %>
    <%= Rouge::Themes::ThankfulEyes.render(scope: '.highlight') %>
  <% when 'tulip' %>
    <%= Rouge::Themes::Tulip.render(scope: '.highlight') %>
  <% end %>
</style>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wordspeaker admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag   'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render partial: 'layouts/syntax_highlight', locals: { syntax_highlight: @setting.syntax_highlight } %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-eval': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <%= link_to 'Dashboard', admin_path, class: 'navbar-brand' %>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to 'Overview', admin_path, class: 'nav-link' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'Settings', admin_settings_path, class: 'nav-link' %>
            </li>
          </ul>
          <ul class="navbar-nav mt-2 mt-md-0">
            <li class="nav-item active">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <% if controller.controller_name == 'dashboard' %>
                <%= link_to 'Dashboard', admin_path, class: 'nav-link active' %>
              <% else %>
                <%= link_to 'Dashboard', admin_path, class: 'nav-link' %>
              <% end %>
            </li>
            <li class="nav-item">
              <% if controller.controller_name == 'articles' %>
                <%= link_to 'Articles', admin_articles_path, class: 'nav-link active' %>
              <% else %>
                <%= link_to 'Articles', admin_articles_path, class: 'nav-link' %>
              <% end %>
            </li>
            <li class="nav-item">
              <% if controller.controller_name == 'categories' %>
                <%= link_to 'Categories', admin_categories_path, class: 'nav-link active' %>
              <% else %>
                <%= link_to 'Categories', admin_categories_path, class: 'nav-link' %>
              <% end %>
            </li>
            <li class="nav-item">
              <% if controller.controller_name == 'tags' %>
                <%= link_to 'Tags', admin_tags_path, class: 'nav-link active' %>
              <% else %>
                <%= link_to 'Tags', admin_tags_path, class: 'nav-link' %>
              <% end %>
            </li>
            <li class="nav-item">
              <% if controller.controller_name == 'images' %>
                <%= link_to 'Images', admin_images_path, class: 'nav-link active' %>
              <% else %>
                <%= link_to 'Images', admin_images_path, class: 'nav-link' %>
              <% end %>
            </li>
            <% if current_user.admin? %>
              <li class="nav-item">
                <% if %w[users registrations].include?(controller.controller_name) %>
                  <%= link_to 'Users', admin_users_path, class: 'nav-link active' %>
                <% else %>
                  <%= link_to 'Users', admin_users_path, class: 'nav-link' %>
                <% end %>
              </li>
            <% end %>
            <li class="nav-item">
              <% if controller.controller_name == 'settings' %>
                <%= link_to 'Settings', admin_settings_path, class: 'nav-link active' %>
              <% else %>
                <%= link_to 'Settings', admin_settings_path, class: 'nav-link' %>
              <% end %>
            </li>
          </ul>
        </nav>

        <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if @setting.google_site_verification.present? %>
      <meta name="google-site-verification" content="<%= @setting.google_site_verification %>" />
    <% end %>
    <title>Wordspeaker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    original_asset_path + '/stylesheets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render partial: 'layouts/syntax_highlight', locals: { syntax_highlight: @setting.syntax_highlight } %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag original_asset_path + '/javascripts/application', 'data-turbolinks-track': 'reload' %>
    <% if @setting.ga_code.present? && !user_signed_in? %>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create', '<%= @setting.ga_code %>', 'auto');ga('send', 'pageview');
      </script>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/init.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wordspeaker admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag   'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-eval': 'false' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <%= link_to 'Initialize', admin_path, class: 'navbar-brand' %>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>